name: Quick CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.x
      - name: Restore packages
        run: dotnet restore
      - name: Build solution
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test --no-build